services:
  s3:
    image: minio/minio
    entrypoint: sh -c "minio server /data --console-address ':9001'"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: localhost
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  create_bucket_and_user:
    image: minio/mc
    entrypoint: sh -c "mc config host add minio http://s3:9000 minio minio123 && mc mb minio/nx-cloud && mc anonymous set public minio/nx-cloud"
    depends_on:
      s3:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

volumes:
  s3_data:
